[package]
name = "openapiv3-adapter"
version.workspace = true
edition.workspace = true

[dependencies]
anyhow.workspace = true
ir = { path = "../ir" }
openapiv3 = "2.2.0"
serde.workspace = true
serde_json.workspace = true
serde_yaml.workspace = true
thiserror.workspace = true
